"""add_calendar_crack_correlation_tables

Revision ID: 1d0cdc9563a9
Revises: 
Create Date: 2026-06-12 07:32:34.733067

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d0cdc9563a9'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('calendar_spreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('commodity', sa.String(length=10), nullable=False),
    sa.Column('contract1', sa.String(length=10), nullable=False),
    sa.Column('contract2', sa.String(length=10), nullable=False),
    sa.Column('price1', sa.Float(), nullable=True),
    sa.Column('price2', sa.Float(), nullable=True),
    sa.Column('spread', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_calendar_spreads_commodity'), 'calendar_spreads', ['commodity'], unique=False)
    op.create_index(op.f('ix_calendar_spreads_id'), 'calendar_spreads', ['id'], unique=False)
    op.create_index('ix_calendar_spreads_lookup', 'calendar_spreads', ['commodity', 'contract1', 'contract2', 'timestamp'], unique=False)
    op.create_index(op.f('ix_calendar_spreads_timestamp'), 'calendar_spreads', ['timestamp'], unique=False)
    op.create_table('correlation_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('computed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('window', sa.String(length=10), nullable=False),
    sa.Column('matrix_type', sa.String(length=20), nullable=False),
    sa.Column('labels_json', sa.Text(), nullable=False),
    sa.Column('matrix_json', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_correlation_snapshots_id'), 'correlation_snapshots', ['id'], unique=False)
    op.create_index('ix_correlation_snapshots_lookup', 'correlation_snapshots', ['window', 'matrix_type', 'computed_at'], unique=False)
    op.create_table('crack_spreads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crude_type', sa.String(length=10), nullable=False),
    sa.Column('crude_price', sa.Float(), nullable=False),
    sa.Column('gasoline_price', sa.Float(), nullable=False),
    sa.Column('distillate_price', sa.Float(), nullable=False),
    sa.Column('crack_spread', sa.Float(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_crack_spreads_crude_type'), 'crack_spreads', ['crude_type'], unique=False)
    op.create_index(op.f('ix_crack_spreads_id'), 'crack_spreads', ['id'], unique=False)
    op.create_index('ix_crack_spreads_lookup', 'crack_spreads', ['crude_type', 'timestamp'], unique=False)
    op.create_index(op.f('ix_crack_spreads_timestamp'), 'crack_spreads', ['timestamp'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_crack_spreads_timestamp'), table_name='crack_spreads')
    op.drop_index('ix_crack_spreads_lookup', table_name='crack_spreads')
    op.drop_index(op.f('ix_crack_spreads_id'), table_name='crack_spreads')
    op.drop_index(op.f('ix_crack_spreads_crude_type'), table_name='crack_spreads')
    op.drop_table('crack_spreads')
    op.drop_index('ix_correlation_snapshots_lookup', table_name='correlation_snapshots')
    op.drop_index(op.f('ix_correlation_snapshots_id'), table_name='correlation_snapshots')
    op.drop_table('correlation_snapshots')
    op.drop_index(op.f('ix_calendar_spreads_timestamp'), table_name='calendar_spreads')
    op.drop_index('ix_calendar_spreads_lookup', table_name='calendar_spreads')
    op.drop_index(op.f('ix_calendar_spreads_id'), table_name='calendar_spreads')
    op.drop_index(op.f('ix_calendar_spreads_commodity'), table_name='calendar_spreads')
    op.drop_table('calendar_spreads')
    # ### end Alembic commands ###
